version: "1.0"
info:
  model: int-scaffold
packages:
- name: ProjectCustomProject
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
services:
- serviceName: project.projectcustom.integrations:testu
  packages:
  - name: ProjectCustomProject
    version: "1.0"
