version: "1.0"
info:
  model: int-scaffold
packages:
- name: ProjectCustomProject
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
- name: CustomPackage
  version: "1.0"
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
- name: FlowDAPkg
  version: "1.0"
  gitServerName: AnushaGITTest
  gitUrl: https://github.webmethods.io/anub
  gitUsername: anub
  gitBranch: main
services:
- serviceName: project.projectcustom.integrations:eflow
  packages:
  - name: ProjectCustomProject
    version: "1.0"
  - name: FlowDAPkg
    version: "1.0"
  - name: CustomPackage
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
